Migrate dev to google cloud
three-consulting/epoc-backend pull request #208
Opened 2023-08-10 12:14 UTC by miikahyttinen

Added a GH action to deploy  backend to Google Run. Action is triggeres on push to `dev`

2023-08-10 12:32 UTC, miikahyttinen commented on .github/workflows/deploy-to-dev.yaml
> +      #      latest=true
@LeadingMoominExpert do we need this?

2023-08-14 07:34 UTC, LeadingMoominExpert requested changes

2023-08-14 07:34 UTC, LeadingMoominExpert commented on .github/workflows/deploy-to-dev.yaml
> +      #      latest=true
```suggestion
      - name: Define image meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}
          tags: |
            type=raw,value=${{ github.sha }}
          labels: |
            org.opencontainers.image.authors=epoc
            org.opencontainers.image.vendor=three.consulting
          flavor: |
            latest=true
```

2023-08-14 07:34 UTC, LeadingMoominExpert commented on .github/workflows/deploy-to-dev.yaml
> +          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
```suggestion
      - name: Build and push image to artifact registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          no-cache: false
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
```

2023-08-14 07:35 UTC, LeadingMoominExpert commented on .github/workflows/deploy-to-dev.yaml
> +  FAR_LOCATION: europe-north1
`FAR_LOCATION` ei oo käytössä

2023-08-14 12:15 UTC, LeadingMoominExpert approved these changes
💯

2023-08-15 06:33 UTC, merged