endpoint for fetching timesheet entries on a given time interval
three-consulting/epoc-backend pull request #97
Opened 2022-05-24 09:44 UTC by ToukoH

2022-05-24 11:09 UTC, mapehe commented
LGTM but @LeadingMoominExpert might be more opinionated when it comes to `epoc-backend`, so I'll request their review.

2022-05-24 12:10 UTC, LeadingMoominExpert requested changes
Custom repository query requires a new test in the repository tests. Changes in the service layer requires a new test on that respective layer

2022-05-27 06:12 UTC, LeadingMoominExpert approved these changes

2022-05-27 08:36 UTC, LeadingMoominExpert approved these changes

2022-05-27 09:00 UTC, merged